version: '3.9'

services:
  postgres:
    platform: linux/amd64
    image: postgres:14
    container_name: db
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: librora
